### ISSUE TITLE
Clarify, how to validate ifcXML that are saved according to ISO 10303-28

### ISSUE THREAD

**Issue by klacol** [buildingSMART/ProductData#13]
There is a sample, that uses the conventitions from ISO 10303-28

https://github.com/buildingSMART/ProductData/blob/master/SampleFiles/NisbetSample/Example1.ifcXML

In the following document is described, how to create an ifcXML based on ISO 10303-28

[ifcXML4 Release summary](http://www.buildingsmart-tech.org/specifications/ifcxml-releases/ifcxml4-release)

[ifcXML4 Specification Methodology](http://www.buildingsmart-tech.org/downloads/ifcxml/ifcxml4/ifcxml4_specification_methodology_v1-1.pdf)

How can such an ifcXML file be validated with the normal XM tools?

**Comment by TLiebich** [comment]
ifcXML files are exchange files according to the XSD schema of the chosen IFC release. For an overview of all IFC releases, see here: http://www.buildingsmart-tech.org/ifc/ (click on "Schemas" in menu)

For each release, open the specification and check "computer interpretable listings". E.g. for IFC4 Add2 see: http://www.buildingsmart-tech.org/ifc/IFC4/Add2TC1/html/link/annex-a.htm - here you find the express and XSD schemas (plus eventually some more, non-official, schemas).

An ifcXML file, that is written against IFC4 Add2 would need to validate against this XSD.

**Comment by klacol** [comment]
Ok, thanks, 

That is, what we are doing here on every commit of a sample. The ifcXML files are validated against the scheme. This is indicated by the green badge on the start page of the repository (build passing).

This [sample](https://github.com/buildingSMART/ProductData/blob/master/SampleFiles/NisbetSample/Example1.ifcXML) is based on IFC 2x3 and has a special header according to ISO 10303-28. Where is the official XSD schema file for IFC 2x3, or should the sample be upgraded to eg. IFC 4 ADD2?

**Comment by klacol** [comment]
Ok, following the recommendation, the schema for the sample file was changed, from IFC 2x3 to IFC4 ADD2. 

Now the validation [fails](https://travis-ci.org/buildingSMART/ProductData/builds/398836147) with this error:

> Example1.ifcXML:3: element iso_10303_28: Schemas validity error : Element '{urn:iso.org:standard:10303:part(28):version(2):xmlschema:common}iso_10303_28': No matching global declaration available for the validation root.

I think, we have to use the schema file for ISO 10303-28 somehow, to validate this file.

**Comment by klacol** [comment]
Ok, the schema file for ISO 10303-28 can be downloaded from this [page](http://www.buildingsmart-tech.org/specifications/ifcxml-releases/ifcxml4-release) ([direct link](http://www.buildingsmart-tech.org/downloads/ifcxml/ifcxml4/cnf.xsd))

It is called `cnf.xsd`.

**Comment by TLiebich** [comment]
sorry, but this is wrong.

ISO 10303-28 **late binding** does not have an XSD schema - it is a specification to transform Express Schema and Data into XML schema and data files. Short intro: https://en.wikipedia.org/wiki/ISO_10303-28 (in IFC, only the late binding part of Part 28 is used)

Each EXPRESS Schema , that is transformed into an conforming XSD following Part 28, has a schema specific XSD. Therefore for each EXPRESS schema of an IFC Release a conforming XSD schema is published.

ISO 10303-28 allows to configure the way, how a particular EXPRESS Schema is transformed into an XSD. An translator for EXPRESS-XSD (for IFC it is ifcDoc) should allow to read in such a configuration. The configuration itself is specified using an XML file, which is specific to each IFC Release. The Part 28 configuration XML file is governed by an own XSD, here cnf.xsd. So the above quoted XSD is not a schema file for ifcXML - only for the configuration file use to generate the IFC Release specific XSD. You can find the configuration file for IFC4 Add2 here: http://www.buildingsmart-tech.org/ifc/IFC4/Add2TC1/html/link/listing-ifc4_add2.htm (last in the list)

N.B. for (almost) all developers such detail is not relevant - just use the XSD for the IFC Schema release.

**Comment by klacol** [comment]
Ok, thanks for the clarification. So, then we should not have to use here the cnf.xsd of ISO 10303-28.

> N.B. for (almost) all developers such detail is not relevant - just use the XSD for the IFC Schema release.

But then I would have to change the [sample file](https://github.com/buildingSMART/ProductData/blob/master/SampleFiles/NisbetSample/Example1.ifcXML), and remove all ISO 10303-28 related elements like

`<ex:iso_10303_28 ...>`
`<ex:iso_10303_28_header ...></ex:iso_10303_28_header>`
 `<ifc:uos id="_0" ...>`

Or are these elements allowed within an ifcXML file? I never used it, but some tools generate the file in this way, and it remains unclear, if this is correct, or not. This should be clarified.

**Comment by TLiebich** [comment]
OK - the file ex.xsd was a XSD schema file that included only the schema-unspecific parts of an P28 conforming XSD - but this only applies to the early drafts of ISO 10303-28 - as used in IFC2x3.

The final ISO 10303-28 allows for including those directly into the schema specific XSD (therefore for IFC4 onwards, there is only one XSD per release).

For old ifcXML files according to IFC2x3 you can find the ex.xsd here: http://www.buildingsmart-tech.org/specifications/ifcxml-releases/ifcxml2x3-release

**Comment by klacol** [comment]
Fixed

With ifcXML we use always IFC4 ADD 1 or higher. Then we can easily validate the ifcXML file with every usual XML tool against the use XSD file. We do not need to the procedures of ISO 10303-28 in this case.
