### ISSUE TITLE
Fix validation errors of the sample file CAFM-Connect-ProductsSample.ifcXML

### ISSUE THREAD

**Issue by klacol** [buildingSMART/ProductData#16]
Fix the following validation errors of the sample file [CAFM-Connect-ProductsSample.ifcXML](https://github.com/buildingSMART/ProductData/blob/master/SampleFiles/CAFM-Connect-ProductsSample/CAFM-Connect-ProductsSample.ifcXML)

> 2018-09-18 05:36:53,591 ERROR - #19=IfcSIUnit is invalid.
>     Issue of type EntityWhereClauses on IfcNamedUnit.WR1.
> 
> 2018-09-18 05:36:53,617 ERROR - #24=IfcSIUnit is invalid.
>     Issue of type EntityWhereClauses on IfcNamedUnit.WR1.
> 
> 2018-09-18 05:36:53,618 ERROR - #29=IfcSIUnit is invalid.
>     Issue of type EntityWhereClauses on IfcNamedUnit.WR1.
> 
> 2018-09-18 05:36:53,618 ERROR - #32=IfcSIUnit is invalid.
>     Issue of type EntityWhereClauses on IfcNamedUnit.WR1.
> 
> 2018-09-18 05:36:53,619 ERROR - #34=IfcSIUnit is invalid.
>     Issue of type EntityWhereClauses on IfcNamedUnit.WR1.
> 
> 2018-09-18 05:36:53,628 ERROR - #40=IfcSIUnit is invalid.
>     Issue of type EntityWhereClauses on IfcNamedUnit.WR1.
> 
> 2018-09-18 05:36:53,629 ERROR - #42=IfcSIUnit is invalid.
>     Issue of type EntityWhereClauses on IfcNamedUnit.WR1.
> 
> 2018-09-18 05:36:53,651 ERROR - #601=IfcPropertySetTemplate is invalid.
>     Issue of type EntityWhereClauses on IfcPropertySetTemplate.UniquePropertyNames.
> 
> 2018-09-18 05:36:53,658 ERROR - #1697=IfcPropertySetTemplate is invalid.
>     Issue of type EntityWhereClauses on IfcPropertySetTemplate.UniquePropertyNames.
> 
> 2018-09-18 05:36:53,680 ERROR - #2539=IfcPropertySetTemplate is invalid.
>     Issue of type EntityWhereClauses on IfcPropertySetTemplate.UniquePropertyNames.
> 
> 2018-09-18 05:36:53,725 ERROR - Exception thrown evaluating where-clause 'IfcRelAssigns.WR1' for #3464.
> System.InvalidOperationException: Das Objekt mit Nullwert muss einen Wert haben.
>    bei System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>    bei Xbim.Ifc4.Functions.IfcCorrectObjectAssignment(Nullable`1 Constraint, IItemSet`1 Objects) in D:\TCBuildAgent\work\77d7b8e93613846d\Xbim.Ifc4\IfcFunctions\Functions.cs:Zeile 585.
>    bei Xbim.Ifc4.Kernel.IfcRelAssigns.ValidateClause(IfcRelAssignsClause clause) in D:\TCBuildAgent\work\77d7b8e93613846d\Xbim.Ifc4\Validation\IfcRelAssigns.cs:Zeile 29.
> 2018-09-18 05:36:53,742 ERROR - #3464=IfcRelAssignsToGroup is invalid.
>     Issue of type EntityWhereClauses on IfcRelAssigns.WR1.

@martin1cerny : Could you give me a hint, how to find the corresponding elements in the file? For instance there is a reference to #2539. I suppose, this is the line number in a step file. How could I find the corresponding element within an ifcXML file?

**Comment by martin1cerny** [comment]
xBIM uses EXPRESS/STEP as its main model so we maintain internal concept of the entity label (essential number on the beginning of the line in STEP21 file). I'll look if I could keep the information about the original XML id. One of the problems might be that some of these objects don't actually have any `id` in XML hence their identity is only placement in the file and that it rather volatile information.

I'll look at what I can do.

**Comment by martin1cerny** [comment]
The latest version of Validator from my PR #17 will write XML entity id if available.

**Comment by klacol** [comment]
Works great, thanks. I could fix all the issues now.

> Check finished. There are 0 errors.
> Press any key to quit.
