### ISSUE TITLE
Title typo

### ISSUE THREAD

**Issue by vdubya** [buildingSMART/ProductData#19]
Minor typo in the ProductData repo description. Offical should be Official. See image.

![image](https://user-images.githubusercontent.com/6257997/45724927-3502b780-bb6d-11e8-9042-0737e56f070c.png)

**Comment by klacol** [comment]
Thanks, I have corrected it. 

By the opportunity I have also written "product data" in lower case. I never know, when to use upper case and when lower case in english :-). Hope this is correct now.
