### ISSUE TITLE
Add file information to the output of the SchemaValidator

### ISSUE THREAD

**Issue by klacol** [buildingSMART/ProductData#25]
The SchemaValidator by @martin1cerny  is an extremly helpful tool.

I have configured the repo, so that all sample files are validated on every commit with a fresh build of the SchemaValidator.

The log output of the SchemaValidator.exe is printed out [here](https://ci.appveyor.com/project/klacol/productdata). The overall result is also displayed on the badge on the home page of the repo (the second one with "Validity of ifcXML files aginst the SchemaValidator").

The log contains the list of errors, if the file is not valid. 

It could also contain some basic information about the file and also an OK message, if the file is valid. The SchemaValidator could print out e.g.

- Name of the file
- Type of the file (ifc or ifcXML)
- Schema version
- Number of elements (perhaps grouped by type)
- Some infos from the header
- Validation result

**Comment by martin1cerny** [comment]
You can close this once you review the changes.

**Comment by klacol** [comment]
Thanks, very helpful. Now the SchemaValidator.exe show this output:

>  SchemaValidator.exe bSDD product room sample.ifcXML
File format: XML (*.ifcXML)
Schema version: IFC4
Model View Definitions: https://github.com/CAFM-Connect/CafmConnectProductData
Number of entities: 186
Number of types: 30
Types frequency
                               IfcSIUnit: 45
               IfcSimplePropertyTemplate: 38
                   IfcDerivedUnitElement: 24
              IfcClassificationReference: 14
                          IfcDerivedUnit: 12
                  IfcPropertyEnumeration: 8
                  IfcPropertySetTemplate: 5
                  IfcPropertySingleValue: 5
          IfcRelAssociatesClassification: 4
                  IfcConversionBasedUnit: 3
                 IfcDimensionalExponents: 3
                      IfcMeasureWithUnit: 3
                         IfcOrganization: 2
                      IfcComplexProperty: 2
                  IfcDocumentInformation: 2
                IfcRelAssociatesDocument: 2
                              IfcProject: 1
                         IfcOwnerHistory: 1
                IfcPersonAndOrganization: 1
                               IfcPerson: 1
                          IfcApplication: 1
                       IfcUnitAssignment: 1
                       IfcProjectLibrary: 1
                          IfcRelDeclares: 1
                            IfcAlarmType: 1
                       IfcClassification: 1
                                IfcAlarm: 1
               IfcRelDefinesByProperties: 1
                          IfcPropertySet: 1
                 IfcRelDefinesByTemplate: 1
OK: \SampleFiles\bSDD product room sample\bSDD product room sample.ifcXML is valid

This is allready a short summary of the classes, that are used in the sample and can lead us the way to define a MVD.
