### ISSUE TITLE
Add example for an EULUMDAT - LDC (Light Distribution Curve) data template

### ISSUE THREAD

**Issue by klacol** [buildingSMART/ProductData#6]
Provide an sample file für EULUMDAT - LDC (Light Distribution Curve) data template
https://en.wikipedia.org/wiki/EULUMDAT

The sample should contain a template and a sheet (with data).

**Comment by klacol** [comment]
A starting point for reading is here:
http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifclightdistributiondata.htm

**Comment by klacol** [comment]
Created sample file with @rheinze.

**Comment by rheinze** [comment]
Add Excel PDT (WG4 TG2) and Eulumdat file.
ifcXML PDT section: Tabel structure of last 2 properties open.
Next step: filling product data in template

**Comment by klacol** [comment]
This issue can be closed. The next step is #40.
